### ISSUE TITLE
[问题] 现在ProjectEvent 发送Http 

### ISSUE THREAD

**Issue by jilliss** [Planshit/ProjectEvent#1]
**简单描述问题**
POST 如何配置 body 参数

curl 命令如下
```bash
curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=693axxx6-7aoc-4bc4-97a0-0ec2sifa5aaa' \
   -H 'Content-Type: application/json' \
   -d '
   {
        "msgtype": "text",
        "text": {
            "content": "hello world"
        }
   }'
```
**截图或视频**
![image](https://user-images.githubusercontent.com/30598952/88992667-96be0c00-d316-11ea-8996-6a8a35323a1d.png)

**软件版本**
在设置>关于中可以查看
核心程序集版本号：
UI程序集版本号：
![image](https://user-images.githubusercontent.com/30598952/88992595-68403100-d316-11ea-9e79-aeabc93aa95b.png)

**Comment by noberumotto** [comment]
:( 非常抱歉这个版本还没加入对post json字符串的支持，所以没法post带嵌套字段的数据。下一个版本会加上。

非常谢谢你的反馈

**Comment by jilliss** [comment]
没有关系，软件很好用 (ง •_•)ง，加油！

**Comment by noberumotto** [comment]
加入了post json字符串支持的0.0.4版本已经发布~
